title: Applications of Circle Theorems with Marine Navigation
description: The earth is a big circle. We have lived there for hundred thousands of years, yet we have not explored it all...
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman 
